import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";

const inter = Inter({ subsets: ["latin"] });
export const metadata: Metadata = {
  title: "PostBox Admin",
  description: "Generated by PostBox Admin",
};
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cn(
          "flex flex-col min-h-screen w-full bg-white text-black",
          inter.className
        )}
      >
        {/* main content */}
        <div>{children}</div>
      </body>
    </html>
  );
}
